#!/bin/sh

eval `/usr/bin/ssh-agent`

export LANG="en_US.UTF-8" \
       LC_CTYPE="en_US.UTF-8"

# https://raspberrypi.stackexchange.com/a/753/38064
xset s noblank
xset s off
xset -dpms

# https://wiki.archlinux.org/index.php/Touchpad_Synaptics#Using_syndaemon
syndaemon -i 0.5 -t -K -R -d

pulseaudio --start

if [ `xrandr | sed -n '/HDMI1/s/HDMI1 \([^ ]*\) .*/\1/p'` == "connected"  ]
then
    xrandr --output eDP1  --mode 1920x1080 --pos 0x1080 --rotate normal \
           --output HDMI1 --mode 1920x1080 --pos 0x0    --rotate normal
fi

# All startup applications are in $HOME/.i3/config
exec /usr/bin/i3
