. /etc/bash.bashrc

MYSQL_PS1='\u@\h \d> '

[ -f ${HOME}/.bash_functions ] && source ${HOME}/.bash_functions
[ -f ${HOME}/.bash_aliases ]   && source ${HOME}/.bash_aliases
[ -f ${HOME}/.bash_arduino ]   && source ${HOME}/.bash_arduino

# rtorrent server
[ -f ${HOME}/.bash_rtsrvr ] && source ${HOME}/.bash_rtsrvr
