# .bashrc for single user

. /etc/bash.bashrc

# own vars
SSH_PRVKEY=/home/vando/.ssh/id_rsa_allaccess
MYSQL_PS1='\u@\h \d> '

# functions
[ -f ${HOME}/.bash_func ] && source ${HOME}/.bash_func

# servers at home
[ -f ${HOME}/.bash_homesrvr ] && source ${HOME}/.bash_homesrvr
