. /etc/bashrc

mkmaildir() { /bin/mkdir -p $1/{cur,new,tmp} ; }
wmclass() { xprop | sed '/WM_CLASS/!d;s/.*= //;s/", "/,/' ; } 

rtorrent()
{
    screen -rmS rtorrent 2> /dev/null
    [[ "$?" -gt 0 ]] && screen -mS rtorrent /usr/bin/rtorrent -o http_capath=/etc/ssl/certs
}
