" Syntax highlighting
set t_Co=256
syntax enable

" Turn off autoindent to paste code
set mouse=n
set pastetoggle=<F3>

" tabs
" https://stackoverflow.com/a/1878983
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

" backup / swap
" The double tailing slash will store files using full paths to avoid clobbering
set backupdir=~/.vim/backup//
set directory=~/.vim/swp//

" shell
" :r !command <opt>
set shellcmdflag+=i

" display the hidden characters
set listchars=tab:→\ ,space:·,nbsp:␣,trail:•,eol:¶,precedes:«,extends:»
highlight NonText ctermfg=DarkGrey
highlight SpecialKey ctermfg=DarkGrey
noremap <F4> :set list!<CR>

" Line numbering
" show/hide: set invnumber
set nu
set numberwidth=3
set cpoptions+=n
highlight LineNr term=bold cterm=NONE ctermfg=DarkGrey ctermbg=NONE

" Statusline
set laststatus=2
highlight StatusLine   cterm=NONE ctermbg=DarkGrey ctermfg=Yellow
highlight StatusLineNC cterm=NONE ctermbg=DarkGrey ctermfg=DarkGrey
highlight VertSplit    cterm=NONE ctermbg=DarkGrey ctermfg=DarkGrey
set statusline=
set statusline+=\  
set statusline+=\[%{mode()}\]
set statusline+=\[%n%H%M%R%W\]
set statusline+=\ %f
set statusline+=%15((L\:\ %l\ C\:\ %c)%)
set statusline+=\ %P 
set statusline+=%= " right-align from now on
set statusline+=\ %y
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\ (%{&fileformat})
set statusline+=\  

" netrw
map <F2> :Sex<CR>
let g:netrw_banner = 0

" syntax for files
autocmd BufNewFile,BufRead ossec.conf set syntax=xml
autocmd BufNewFile,BufRead *_nagios2.cfg set filetype=nagios

" split (Ctrl-w s)
" https://robots.thoughtbot.com/vim-splits-move-faster-and-more-naturally
set splitbelow
set splitright

" tabs
" leader = \
nnoremap <leader>t :tabnew<CR>
nnoremap <leader>n :tabn<CR>
nnoremap <leader>p :tabp<CR>

" Gist
let g:gist_show_privates = 1
let g:gist_post_private = 1
let g:gist_detect_filetype = 1
let g:gist_clip_command = 'xclip -selection clipboard'

" Vundle begin
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" vim +PluginInstall +qall
Plugin 'VundleVim/Vundle.vim'
Plugin 'ekalinin/Dockerfile.vim'
Plugin 'saltstack/salt-vim'
Plugin 'PotatoesMaster/i3-vim-syntax'
Plugin 'mattn/webapi-vim'
Plugin 'mattn/gist-vim'
Plugin 'Matt-Deacalion/vim-systemd-syntax'
Plugin 'wellle/targets.vim'
Plugin 'vim-scripts/nagios-syntax'
call vundle#end()
filetype plugin indent on
