" Syntax highlighting
set t_Co=256
syntax enable

" mouse
set mouse=n

" Clipboard
set pastetoggle=<F3>
nnoremap Y y$

" tabs
" https://stackoverflow.com/a/1878983
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

" backup / swap
set nobackup
set noswapfile

" shell
" :r !command <opt>
set shellcmdflag+=i

" display the hidden characters
set listchars=tab:→\ ,space:·,nbsp:␣,trail:•,eol:¶,precedes:«,extends:»
highlight NonText ctermfg=DarkGrey
highlight SpecialKey ctermfg=DarkGrey
noremap <silent> <F4> :set list!<CR>

" Line numbering
" show/hide: set invnumber
set nu
set numberwidth=3
set cpoptions+=n
highlight LineNr term=bold cterm=NONE ctermfg=DarkGrey ctermbg=NONE

" Statusline
set laststatus=2
highlight StatusLine   cterm=NONE ctermbg=DarkGrey ctermfg=Yellow
highlight StatusLineNC cterm=NONE ctermbg=DarkGrey ctermfg=DarkGrey
highlight VertSplit    cterm=NONE ctermbg=DarkGrey ctermfg=DarkGrey
set statusline=
set statusline+=\  
set statusline+=\[%{mode()}\]
set statusline+=\[%n%H%M%R%W\]
set statusline+=\ %f
set statusline+=%15((L\:\ %l\ C\:\ %c)%)
set statusline+=\ %P 
set statusline+=%= " right-align from now on
set statusline+=\ %y
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\ (%{&fileformat})
set statusline+=\  

" netrw
map <silent> <F2> :Lexplore<CR>
autocmd BufEnter * if ( winnr("$") == 1 && &filetype ==# 'netrw' ) | q | endif
let g:netrw_banner=0
let g:netrw_winsize=-20
let g:netrw_list_hide='^\./$,^\.git/$'

" syntax for files
autocmd BufNewFile,BufRead ossec.conf set syntax=xml
autocmd BufNewFile,BufRead *_nagios2.cfg set filetype=nagios

" split (Ctrl-w s)
" https://robots.thoughtbot.com/vim-splits-move-faster-and-more-naturally
set splitbelow
set splitright

" tabs
" leader = \
nnoremap <leader>t :tabnew<CR>
nnoremap <leader>n :tabn<CR>
nnoremap <leader>p :tabp<CR>
highlight TabLineSel cterm=NONE ctermbg=DarkGrey ctermfg=Yellow
highlight TabLine cterm=NONE ctermbg=DarkGrey ctermfg=Black
highlight TabLineFill ctermfg=DarkGrey

" wrapped text: jumps to the next row in the editor (instead of the next line)
nnoremap <Down> gj
nnoremap <Up> gk

" split lines
" https://superuser.com/a/611420
function! BreakHere()
    s/^\(\s*\)\(.\{-}\)\(\s*\)\(\%#\)\(\s*\)\(.*\)/\1\2\r\1\4\6
    call histdel("/", -1)
endfunction
nnoremap z :<C-u>call BreakHere()<CR>

" Gist
let g:gist_show_privates = 1
let g:gist_post_private = 1
let g:gist_detect_filetype = 1
let g:gist_clip_command = 'xclip -selection clipboard'

" Vundle begin
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" vim +PluginInstall +qall
Plugin 'VundleVim/Vundle.vim'
Plugin 'ekalinin/Dockerfile.vim'
Plugin 'saltstack/salt-vim'
Plugin 'PotatoesMaster/i3-vim-syntax'
Plugin 'mattn/webapi-vim'
Plugin 'mattn/gist-vim'
Plugin 'Matt-Deacalion/vim-systemd-syntax'
Plugin 'wellle/targets.vim'
Plugin 'vim-scripts/nagios-syntax'
call vundle#end()
filetype plugin indent on
